name: Tests

on:
  push:
    branches: [ "master", "v2" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: run tests
      run: ./run_tests.sh
