name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: run tests
      run: docker build . --file Dockerfile --tag e2e-tests-playground:$(date +%s)
